const sampleListings = [
  {
    title: "Sea View Villa",
    description: "Luxury villa with ocean-facing balcony",
    image:
      "https://r1imghtlak.mmtcdn.com/4b78346b-5af0-4971-8b6f-fbfc68e8bc5e.jpg",
    price: 3500,
    location: "Calangute, Goa",
    country: "India",
  },
  {
    title: "Hilltop Cottage",
    description: "Peaceful stay surrounded by hills and greenery",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    price: 1800,
    location: "Manali, Himachal Pradesh",
    country: "India",
  },
  {
    title: "City Apartment",
    description: "Modern apartment in the heart of the city",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 2200,
    location: "Bangalore, Karnataka",
    country: "India",
  },
  {
    title: "Desert Camp",
    description: "Traditional desert stay with cultural experience",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 1500,
    location: "Jaisalmer, Rajasthan",
    country: "India",
  },
  {
    title: "Backwater Homestay",
    description: "Calm waterside home with local food",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427",
    price: 2000,
    location: "Alappuzha, Kerala",
    country: "India",
  },
  {
    title: "Heritage Haveli",
    description: "Royal stay in a traditional haveli",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 2800,
    location: "Jaipur, Rajasthan",
    country: "India",
  },
  {
    title: "Forest Retreat",
    description: "Nature retreat near wildlife sanctuary",
    image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c",
    price: 1700,
    location: "Jim Corbett, Uttarakhand",
    country: "India",
  },
  {
    title: "Lakeside Resort",
    description: "Relaxing resort with lake view rooms",
    image: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
    price: 2600,
    location: "Udaipur, Rajasthan",
    country: "India",
  },
  {
    title: "Budget Guest House",
    description: "Affordable stay for solo travelers",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    price: 900,
    location: "Varanasi, Uttar Pradesh",
    country: "India",
  },
  {
    title: "Mountain View Resort",
    description: "Resort with stunning Himalayan views",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: 3200,
    location: "Nainital, Uttarakhand",
    country: "India",
  },
  {
    title: "Beach Hut",
    description: "Simple beach hut with sea breeze",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 1400,
    location: "Baga, Goa",
    country: "India",
  },
  {
    title: "Luxury Penthouse",
    description: "Premium penthouse with city skyline view",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 4200,
    location: "Mumbai, Maharashtra",
    country: "India",
  },
  {
    title: "Eco Stay",
    description: "Environment friendly eco stay",
    image: "https://images.unsplash.com/photo-1470163395405-d2b80e7450ed",
    price: 1600,
    location: "Coorg, Karnataka",
    country: "India",
  },
  {
    title: "Temple View Lodge",
    description: "Stay near famous temples",
    image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
    price: 1100,
    location: "Madurai, Tamil Nadu",
    country: "India",
  },
  {
    title: "Tea Garden Bungalow",
    description: "Bungalow surrounded by tea plantations",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    price: 2300,
    location: "Munnar, Kerala",
    country: "India",
  },
  {
    title: "Snow View Cabin",
    description: "Cozy cabin with snow views",
    image: "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66",
    price: 3000,
    location: "Gulmarg, Kashmir",
    country: "India",
  },
  {
    title: "City Budget Hotel",
    description: "Comfortable stay at budget price",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    price: 1200,
    location: "Patna, Bihar",
    country: "India",
  },
  {
    title: "Highway Motel",
    description: "Convenient stopover on highway",
    image: "https://images.unsplash.com/photo-1522156373667-4c7234bbd804",
    price: 1000,
    location: "Agra, Uttar Pradesh",
    country: "India",
  },
  {
    title: "Sunset View Resort",
    description: "Perfect sunset views every evening",
    image: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21",
    price: 3400,
    location: "Varkala, Kerala",
    country: "India",
  },

  {
    title: "Island Retreat",
    description: "Private island style experience",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    price: 3800,
    location: "Andaman & Nicobar",
    country: "India",
  },
  {
    title: "Royal Palace Stay",
    description: "Live like royalty in palace rooms",
    image: "https://images.unsplash.com/photo-1537726235470-8504e3beef77",
    price: 5000,
    location: "Jodhpur, Rajasthan",
    country: "India",
  },
  {
    title: "Farm Stay",
    description: "Experience village life and farming",
    image: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
    price: 1300,
    location: "Nashik, Maharashtra",
    country: "India",
  },
  {
    title: "Studio Apartment",
    description: "Compact and comfortable studio",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    price: 2100,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Cliffside Resort",
    description: "Resort located on scenic cliffs",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 3600,
    location: "Lonavala, Maharashtra",
    country: "India",
  },
  {
    title: "Pilgrim Rest House",
    description: "Simple stay for pilgrims",
    image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
    price: 800,
    location: "Ayodhya, Uttar Pradesh",
    country: "India",
  },
  {
    title: "Luxury Farm Villa",
    description: "Premium villa in countryside",
    image: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
    price: 3900,
    location: "Chandigarh",
    country: "India",
  },
  {
    title: "City Business Hotel",
    description: "Perfect for business travelers",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    price: 2700,
    location: "Hyderabad, Telangana",
    country: "India",
  },
  {
    title: "Jungle Tree House",
    description: "Stay high above in jungle trees",
    image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c",
    price: 2500,
    location: "Wayanad, Kerala",
    country: "India",
  },
];

module.exports = { data: sampleListings };
